name: factchecker
version: 1.0.0
description: 실시간 미디어 콘텐츠 진위 검증 및 AR 시각화 시스템

dependencies:
  # 서버 프레임워크
  express: ^4.18.2
  cors: ^2.8.5
  helmet: ^7.1.0
  compression: ^1.7.4
  
  # 데이터베이스
  mongoose: ^8.1.0
  redis: ^4.6.12
  ioredis: ^5.3.2
  
  # 인증 및 보안
  jsonwebtoken: ^9.0.2
  bcryptjs: ^2.4.3
  passport: ^0.7.0
  passport-jwt: ^4.0.1
  
  # API 및 통신
  axios: ^1.6.5
  socket.io: ^4.7.4
  node-fetch: ^3.3.2
  
  # 로깅 및 모니터링
  winston: ^3.11.0
  morgan: ^1.10.0
  pino: ^8.17.2
  
  # 유틸리티
  dotenv: ^16.3.1
  joi: ^17.11.0
  lodash: ^4.17.21
  moment: ^2.30.1
  
  # WebXR 및 AR
  three: ^0.160.0
  webxr-polyfill: ^2.0.3
  
  # 성능 최적화
  web-streams-polyfill: ^3.3.2
  abort-controller: ^3.0.0
  
  # 테스트
  jest: ^29.7.0
  supertest: ^6.3.3
  
devDependencies:
  # 개발 도구
  nodemon: ^3.0.2
  eslint: ^8.56.0
  prettier: ^3.1.1
  typescript: ^5.3.3
  ts-node: ^10.9.2
  
  # 타입 정의
  "@types/node": ^20.10.6
  "@types/express": ^4.17.21
  "@types/jest": ^29.5.11
  
  # 빌드 도구
  webpack: ^5.89.0
  webpack-cli: ^5.1.4
  babel-loader: ^9.1.3
  
  # 코드 품질
  husky: ^8.0.3
  lint-staged: ^15.2.0
  
scripts:
  start: node src/app.js
  dev: nodemon src/app.js
  build: webpack --mode production
  test: jest --coverage
  lint: eslint . --fix
  format: prettier --write "**/*.{js,ts,json}"

engines:
  node: ">=18.0.0"
  npm: ">=8.0.0"

repository:
  type: git
  url: https://github.com/yourusername/factchecker.git

author: Your Name
license: MIT 